name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build linux
      run: cargo build --release
    - name: Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "$GITHUB_HEAD_REF-linux"
        path: target/release/autoconfig
